### ISSUE TITLE
insteadOf not picked up in GHA global git config

### ISSUE THREAD

**Issue by fredrikaverpil** [jelmer/dulwich#983]
Hi @jelmer 👋 

### Background

- I'm in a private org with private repos.
- We are running Poetry to maintain/install dependencies in our Python projects and we currently do not have an internal pypi-like package repository. Instead we install our Python packages via git links.
- Poetry 1.1.13 is working fine today in our setup with GitHub Actions, which makes use if rewriting URLs using insteadOf. We have this in our GitHub Actions internal/private custom actions:

```
git config --global --replace-all url.https://github.com/.insteadOf ssh://git@github.com/
git config --global --add url.https://github.com/.insteadOf git@github.com:
```

- When trying Poetry 1.2.0b2, I was getting errors ([discord thread](https://discord.com/channels/487711540787675139/487711540787675143/989529490449375322)) because now dulwich is used under the hood which did not implement reading the git config's [insteadOf](https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf).
- Recently, you added support for insteadOf in #982 (issue #706)

### Problem description

Since there is now support in dulwich for `insteadOf`, I installed dulwich on top of the existing poetry installation in GHA to give this a test run.

<details>
<summary>GHA workflow code</summary>

```yaml
name: poetry

on:
  workflow_dispatch:
  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      # redacted: internal checkout action

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: "Install/setup pipx"
        uses: fredrikaverpil/setup-pipx@v1.5

      - run: pipx install poetry==1.2.0b2

      - run: pipx runpip poetry install -U git+https://github.com/jelmer/dulwich.git@master

      # redacted: internal git config action which executes `git config --global` commands

      - run: poetry install
```
</details>

However, when running this GHA workflow I'm still getting errors which indicate that the git config is not being read:

<details>
<summary>GHA log and traceback</summary>

```
$ poetry install

...
  • Installing black (22.3.0)
  • Installing factory-boy (2.12.0)
  HangupException
  The remote server unexpectedly closed the connection.
  at ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/dulwich/protocol.py:232 in read_pkt_line
      228│ 
      229│         try:
      230│             sizestr = read(4)
      231│             if not sizestr:
    → 232│                 raise HangupException()
      233│             size = int(sizestr, 16)
      234│             if size == 0:
      235│                 if self.report_activity:
      236│                     self.report_activity(4, "read")
The following error occurred when trying to handle this error:
  HangupException
  Warning: Permanently added the ECDSA host key for IP address '192.30.255.113' to the list of known hosts.
  git@github.com: Permission denied (publickey).
  at ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/dulwich/client.py:1123 in fetch_pack
      1119│         with proto:
      1120│             try:
      1121│                 refs, server_capabilities = read_pkt_refs(proto.read_pkt_seq())
      1122│             except HangupException:
    → 1123│                 raise _remote_error_from_stderr(stderr)
      1124│             (
      1125│                 negotiated_capabilities,
      1126│                 symrefs,
      1127│                 agent,
  • Installing flake8-bandit (3.0.0)
  • Installing flake8-bugbear (22.4.25)
  • Installing isort (5.10.1)
  HangupException
  The remote server unexpectedly closed the connection.
  at ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/dulwich/protocol.py:232 in read_pkt_line
      228│ 
      229│         try:
      230│             sizestr = read(4)
      231│             if not sizestr:
    → 232│                 raise HangupException()
      233│             size = int(sizestr, 16)
      234│             if size == 0:
      235│                 if self.report_activity:
      236│                     self.report_activity(4, "read")
The following error occurred when trying to handle this error:
  HangupException
  git@github.com: Permission denied (publickey).
  at ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/dulwich/client.py:1123 in fetch_pack
      1119│         with proto:
      1120│             try:
      1121│                 refs, server_capabilities = read_pkt_refs(proto.read_pkt_seq())
      1122│             except HangupException:
    → 1123│                 raise _remote_error_from_stderr(stderr)
      1124│             (
      1125│                 negotiated_capabilities,
      1126│                 symrefs,
      1127│                 agent,
  • Installing mkdocs-awesome-pages-plugin (2.7.0)
  • Installing mkdocs-material (8.3.4)
  • Installing mypy (0.961)
Error: Process completed with exit code 1.
...

```
</details>

I'm now wondering what may be the issue here. Is it possible that dulwich is only reading the repo's config and not the global config?
